/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jstarczewski.kstate.generate

import org.gradle.api.Plugin
import org.gradle.api.Project
import java.io.File

class KstateGeneratePlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val objects = project.objects

        val config = objects.domainObjectContainer(GenerationSpecification::class.java) { name ->
            objects.newInstance(GenerationSpecification::class.java, name)
        }

        project.extensions.add("generationConfig", config)

        if (project.extensions.getByName("generationConfig") != null) {
            config.all { spec ->
                project.tasks.register(GENERATE_SWIFT_TEMPLATES_TASK_NAME, GenerateSwiftTemplatesTask::class.java) {
                    it.outputDir.set(File(spec.outputDir.get()))
                    it.sharedModuleName.set(spec.sharedModuleName.get())
                }
            }
        } else {
            project.tasks.register(GENERATE_SWIFT_TEMPLATES_TASK_NAME, GenerateSwiftTemplatesTask::class.java) {
                it.outputDir.set(File("${project.projectDir}/GeneratedSwiftWrappers/"))
                it.sharedModuleName.set(project.name)
            }
        }
    }

    private companion object {

        private const val GENERATE_SWIFT_TEMPLATES_TASK_NAME = "generateSwiftTemplates"
    }
}
