/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jstarczewski.kstate.generate

import kotlin.test.Test

class KstateGeneratePluginTest {
    @Test
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
    }
}
