/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.jstarczewski.kstate.generate

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test

class KstateGeneratePluginTest {
    @Test
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.jstarczewski.kstate.generate")
    }
}
